apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: 10.0.0.140:5000/dev/nginx
        ports:
        - containerPort: 80
          hostPort: 10080
