apiVersion: v1
kind: ReplicationController
metadata:
  name: gogo
spec:
  replicas: 2
  selector:
    name: gogo
  template:
    metadata:
      labels:
        name: gogo
    spec:
      containers:
      - name: gogo
        image: 10.0.0.140:5000/app/gogo:22
        ports:
        - containerPort: 8080
          hostPort: 8888
